# Generated by Django 2.0.5 on 2018-07-10 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtodo',
            name='time_added',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
