# Generated by Django 2.0.5 on 2018-07-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_auto_20180710_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtodo',
            name='time_added',
        ),
    ]
